export const storyRootConstants = {
  SET_STORY_ROOTS: "SET_STORY_ROOTS",
  CREATE_STORY_ROOT_SUCCESS: "CREATE_STORY_ROOT_SUCCESS",
  FETCH_STORY_ROOT: "FETCH_STORY_ROOT",
  EDIT_STORY_ROOT_SUCCESS: "EDIT_STORY_ROOT_SUCCESS",
  DELETE_STORY_ROOT_SUCCESS: "DELETE_STORY_ROOT_SUCCESS",
  UN_SET_STORY_ROOT: "UN_SET_STORY_ROOT",
  FETCH_STORY_ROOT_TO_EDIT: "FETCH_STORY_ROOT_TO_EDIT",
  SET_STORY_ROOTS_FOR_VISITED_AUTHOR: "SET_STORY_ROOTS_FOR_VISITED_AUTHOR"
};

export const textConstants = {
  ADD_TEXT: "ADD_TEXT",
  SET_TEXTS: "SET_TEXTS",
  EDIT_TEXT: "EDIT_TEXT",
  UPDATE_TEXT: "UPDATE_TEXT",
  DELETE_TEXT: "DELETE_TEXT",
  LOAD_TEXT: "LOAD_TEXT",
  UNLOAD_TEXT: "UNLOAD_TEXT"
};

export const userConstants = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_START: "LOGIN_START",
  LOGOUT: "LOGOUT",
  SET_AUTHORS: "SET_AUTHORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  GET_ERRORS: "GET_ERRORS"
};

export const authorConstants = {
  ADD_AUTHOR_SUCCESS: "ADD_AUTHOR_SUCCESS",
  FETCH_AUTHOR: "FETCH_AUTHOR",
  GET_AUTHOR: "GET_AUTHOR",
  EDIT_AUTHOR_SUCCESS: "EDIT_AUTHOR_SUCCESS",
  DELETE_AUTHOR_SUCCESS: "DELETE_AUTHOR_SUCCESS",
  SELECT_AUTHOR: "SELECT_AUTHOR",
  ONSELECT_AUTHOR: "ONSELECT_AUTHOR",
  UN_FOLLOW_SUCCESS: "UN_FOLLOW_SUCCESS",
  FOLLOW_SUCCESS: "FOLLOW_SUCCESS",
  UN_SET_AUTHOR: "UN_SET_AUTHOR"
};
